[".local/share/zsh/powerlevel10k"]
    type = "git-repo"
    url = "https://github.com/romkatv/powerlevel10k.git"
    exact = true
    clone.args = ["--depth=1"]
    refreshPeriod = "168h"

[".local/share/zsh/zsh-syntax-highlighting"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
    exact = true
    stripComponents=1
    exclude = ["*/tests", "*/docs", "*/images", "*/*.md", "*/*git*", "*/Makefile"]
    refreshPeriod = "168h"

[".local/share/zsh/zsh-autosuggestions"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-autosuggestions"
    exact = true
    clone.args = ["--depth=1"]
    refreshPeriod = "168h"

[".local/share/zsh/zsh-history-substring-search"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-history-substring-search.git"
    exact = true
    clone.args = ["--depth=1"]
    refreshPeriod = "168h"
