#!/bin/zsh
[ -z "$TMUX"  ] && exec tmux new-session

#                                Powerlevel10k
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "$XDG_CACHE_HOME/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "$XDG_CACHE_HOME/p10k-instant-prompt-${(%):-%n}.zsh"
fi
source $XDG_DATA_HOME/zsh/powerlevel10k/powerlevel10k.zsh-theme
[[ -f $XDG_CONFIG_HOME/zsh/p10k.zsh ]] && source $XDG_CONFIG_HOME/zsh/p10k.zsh

# Load aliases
source $XDG_CONFIG_HOME/shell/aliasrc

# Options
setopt autocd                   # Type directory name to cd into it.
setopt interactive_comments     # Allow comments in interactive shell.
stty stop undef <$TTY >$TTY	    # Disable Ctrl-S to freeze terminal.

# History in cache directory
HISTSIZE=10000000
SAVEHIST=10000000
HISTFILE="${XDG_CACHE_HOME}/zsh/history"	
[[ -f $HISTFILE ]] || \mkdir -p $(dirname $HISTFILE)

# Basic auto/tab complete:
autoload -U compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit
_comp_options+=(globdots)		# Include hidden files.


# vi mode
bindkey -v
export KEYTIMEOUT=1

# Use vim keys in tab complete menu:
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history
bindkey -v '^?' backward-delete-char

# Change cursor shape for different vi modes.
function zle-keymap-select () {
    case $KEYMAP in
        vicmd) echo -ne '\e[1 q';;      # block
        viins|main) echo -ne '\e[5 q';; # beam
    esac
}
zle -N zle-keymap-select
zle-line-init() { zle -K viins; echo -ne "\e[5 q" }
zle -N zle-line-init
echo -ne '\e[5 q' # Use beam shape cursor on startup.
preexec() { echo -ne '\e[5 q' ;} # Use beam shape cursor for each new prompt.

# Plugins
# Lazyshell
source $XDG_DATA_HOME/zsh/lazyshell/lazyshell.zsh

# zsh-autosuggestions
source $XDG_DATA_HOME/zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

# zsh-syntax-highlighting
source $XDG_DATA_HOME/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# zsh-history-substring-search
source $XDG_DATA_HOME/zsh/zsh-history-substring-search/zsh-history-substring-search.zsh
    # search history with up/down or j/k (in vi mode)
    bindkey '^[[A' history-substring-search-up
    bindkey '^[[B' history-substring-search-down
    bindkey -M vicmd 'k' history-substring-search-up
    bindkey -M vicmd 'j' history-substring-search-down
    export HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_FOUND=default
