[general]
import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/colors/catppuccin-latte.toml"
  # "~/.config/alacritty/colors/catppuccin-frappe.toml"
  # "~/.config/alacritty/colors/catppuccin-macchiato.toml"
  # "~/.config/alacritty/colors/catppuccin-mocha.toml"
  # "~/.config/alacritty/colors/monokai-charcoal.toml"
  # "~/.config/alacritty/colors/onedark.toml"
  "~/.config/alacritty/colors/kanagawa_darkwave.toml"
]

[env]
term = "xterm-256color"

[cursor]
blink_interval = 350
thickness = 0.15
unfocused_hollow = true

[cursor.style]
blinking = "Always"
shape = "Beam"

[font]
size = 10.0

[font.bold]
family = "FiraCode Nerd Font"

[font.italic]
family = "FiraCode Nerd Font"

[font.normal]
family = "FiraCode Nerd Font"
style = "Medium"

[window]
decorations = "Full"
opacity = 1

[window.dimensions]
columns = 80
lines = 24

[window.padding]
x = 0
y = 0
